### ISSUE TITLE
Diffin' YAML with multiple document sections

### ISSUE THREAD

**Issue by rjk9w5** [sahilm/yamldiff#1]
I have some yaml files that need diffin' but they are composed of multiple "documents" with the --- separator. 

```
version: 4.4.4
file_name: name_of_file.yml
additional_header_info: header_info...
---  # <- this stops the diffin'
config_opt: value
config_data: data...
```

When I do the diff it will tell me if the first part is different but the second part is skipped.

**Comment by sahilm** [comment]
Thanks for filing this issue. Sadly this tool is for diff-ing single YAML documents. Sorry!

**Comment by corneliusroemer** [comment]
Would be great to diff multiple files! Maybe you can add a limitation section to the README?
