### ISSUE TITLE
yamldiff can experience type coercion

### ISSUE THREAD

**Issue by szabado** [sahilm/yamldiff#10]
Yamldiff suffers from a type coercion bug/feature from the underlying godebug library: https://github.com/kylelemons/godebug/issues/21

Example files:
```
0.123: "a value"
```

```
"0.123": "a value"
```

These two will have no diff, despite the values being different.

**Comment by sahilm** [comment]
Diff library migrated to https://github.com/r3labs/diff/. Please reopen if still an issue.
