### ISSUE TITLE
Is the stat(...) call really necessary?

### ISSUE THREAD

**Issue by JensRantil** [sahilm/yamldiff#16]
From what I understand, [`stat(...)`](https://github.com/sahilm/yamldiff/blob/master/main.go#L60) is only used to check that a file exist. But really, https://github.com/sahilm/yamldiff/blob/3a067f14615afd8347b396a24cd800810bcec41f/main.go#L45-L52 will fail if any of the files don't exist. Additionally, https://github.com/sahilm/yamldiff/blob/master/main.go#L80 will fail in other ways, such as read permissions being incorrect.

**Comment by sahilm** [comment]
I want to fail with a good error message.
