### ISSUE TITLE
Are `--file` flags really necessary?

### ISSUE THREAD

**Issue by JensRantil** [sahilm/yamldiff#18]
Readme file gives

    yamldiff --file1 /path/to/yamlfile1.yml --file2 /path/to/yamlfile2.yml

as an example. Given that I assume every invocation requires two files as input, maybe

    yamldiff /path/to/yamlfile1.yml /path/to/yamlfile2.yml

(similar to good'ole `diff`) is nicer?

**Comment by sahilm** [comment]
No. Fixed in https://github.com/sahilm/yamldiff/pull/9
